baseURL = "https://cyrusolinger.com/"
languageCode = "en-us"
title = "Cyrus Olinger"
theme = "cyrus-dark"

[params]
author = "Cyrus Olinger"
description = "Publicizing my journey into cybersecurity."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3
